defaults:
  - base

trainer:
  experiment_name: TicTacToe-Math
  save_freq: 20

actor_rollout_ref:
  rollout:
    max_model_len: 6000  # 修改之后还是会超出默认的最大长度3600

es_manager:  # 数值沿用原始设定，并没有缩小规模
  format_penalty: -0.1
  train:
    env_groups: 10 # 8 + 2
    # under the same group, the env config and env seed are ensured to be equal
    group_size: 16  # 16
    env_configs:
      tags: ["TicTacToe", "MathTrain"]
      n_groups: [8, 2] # If not set, all env names divide nums equally. Under the same group, the env config and env seed (prompt) are equal in each generation
  val:
    env_groups: 32 # 256 -> 32
    group_size: 1 # should be set to 1 because when val temperature is set to 0 and group size > 1, there will be repetitive prompts which leads to same trajectory.
    env_configs:
      tags: ["TicTacToe", "MathTest"]
      n_groups: [16, 16] # [256] -> [32] # TODO: If not set, all env names divide nums equally. Under the same group, the env config and env seed (prompt) are equal in each generation

